version: '3.8' 

services:
  qdrant:
    image: qdrant/qdrant:latest 
    container_name: qdrant_db   
    restart: unless-stopped    
    ports:
      - "6333:6333" 
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage 
   
volumes:
  qdrant-storage: 